---
title: "final paper"
author: "Yi-jung Wu"
date: "4/22/2020"
output:
  pdf_document: default
  html_document: default
---

## R Markdown

I plan to do my project using a paper that I have been working on it. The paper’s title is "Explore How School and Student-Level Factors Influence Students’ Mathematics Performance: Using 2012 PISA Hong Kong Sample". I have my writing and data analysis, but I hope to revise it into the R markdown format so I can knit it to the pdf.I would like to use this final project to learn how to execute some commands and show the results in the text if I want to and know how not to show the result if I do not want to. I would like to know how to create the HLM output table automatically, or should I create in word or excel and then manually create it and save it as a photo and then insert it? I would like to learn how to display two graphs in one row in the text. I would like to show I can type mathematics formula in the text or a single row. I would like to show my understanding to cite references in APA format correctly.  